spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.141.4.199/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 10.141.4.199
    port: 6379
    password:
#    设置全局只要是空的字段都不返回到结果中
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    #设置日志的格式
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
##  file: /var/log/tomcat/sell.log 指定日志输出文件
##  指定类的日志级别是debug,默认是info
#  level:
#     com.imooc.LoggerTest: debug
wechat:
    mpAppId: wx3cd7106dd645dbba
    mpAppSecret: 7482cf813d523521829a2a54ec1478c0
    openAppId: oOAAb0s9tWTtnmWTPSat_2otgsQQ
    openAppSecret: abcde
    mchId: 1445123131
    mchKey: 012f1sf15swf1r2f1s12
    Keypath: F:\key
    notifyUrl: localhost:8080/sell/pay/notify
    templateId:
      orderStatus: 6Wxmcia348Vgg2xb9zVFBCipVP-02a0w06D42ZxgD6A
logging:
   level:
     com.imooc.dataobject.mapper: trace #mybatis显示出sql语句
mybatis:
  mapper-locations: classpath:mapper/*.xml #找到mybatis的xml文件