spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.141.4.199/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    设置全局只要是空的字段都不返回到结果中
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    #设置日志的格式
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
##  file: /var/log/tomcat/sell.log 指定日志输出文件
##  指定类的日志级别是debug,默认是info
#  level:
#     com.imooc.LoggerTest: debug
wechat:
    mpAppId: 1111
    mpAppSecret: qwdeafefrffasa
    mchId: 1445123131
    mchKey: 012f1sf15swf1r2f1s12
    Keypath: F:\key
    notifyUrl: localhost:8080/sell/pay/notify
