spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.141.4.199/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    #设置日志的格式
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
##  file: /var/log/tomcat/sell.log 指定日志输出文件
##  指定类的日志级别是debug,默认是info
#  level:
#     com.imooc.LoggerTest: debug